language: csharp
mono: none

notifications:
  email: false

branches:
  only:
    - master

matrix:
  include:
    - os: linux 
      dist: trusty 
      dotnet: 2.1
    - os: osx
      dotnet: 2.1.300
      osx_image: xcode8.3

before_install:
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get -qq update; fi
  - if [ $TRAVIS_OS_NAME = osx ]; then ulimit -S -n 4096; fi
